### ISSUE TITLE
IE11 Compatability

### ISSUE THREAD

**Issue by robmcguinness** [rubensworks/relative-to-absolute-iri.js#5]
Let me know if you would be interested in making this library compatible with IE11. Currently this lib causes IE11 to emit a syntax error because of the template strings. I can submit a PR to modify the build process to compile down to IE11.

**Comment by rubensworks** [comment]
Browser compatibility is not something this library aims for. If support for specific browsers is needed, I would recommend adding Babel into your Webpack/Browserify toolchain to transpile the JS down to the level you desire.

That being said, I see that there is only a single templated string usage, so getting rid of that would not  be a real problem. But I would suspect that you would run into other problems in the future with other dependencies that are using JS features that are not supported by IE11, so I think transpiling is the way to go here.

**Comment by robmcguinness** [comment]
Understood. Unfortunately the toolkit that we are using isn't compiling all 3rd party modules from within `node_modules` at this time but that is something that needs to be fixed regardless. Thanks for feedback!
